### ISSUE TITLE
部署完成后用不了

### ISSUE THREAD

**Issue by ahpxex** [taurusni/V2ray_tls_ws#1]
2021/06/03 01:03:32 [Warning] [290604985] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://www.ahpxchina.cn:23334/0e453f1e79e1a35/): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by taurusni** [comment]
修改了下，在Ubuntu18.04测试了可以用了，用了bbr效果挺明显，因人而异

部署完成后，看看v2ray启动没有
`ps -ef | grep v2ray`
=> nobody   28759     1  0 16:12 ?        00:00:00 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

**Comment by ahpxex** [comment]
> 修改了下，在Ubuntu18.04测试了可以用了，用了bbr效果挺明显，因人而异
> 
> 部署完成后，看看v2ray启动没有
> `ps -ef | grep v2ray`
> => nobody 28759 1 0 16:12 ? 00:00:00 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

谢谢！可以工作了！
